plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" apply false
    id 'net.neoforged.moddev' version "${neoforge_moddev_version}" apply false
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        mavenCentral()
        maven { url = 'https://maven.blamejared.com' }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
    }
}

subprojects {
    plugins.withId('java') {
        def targetJavaVersion = rootProject.java_version.toInteger()

        java {
            def javaVersion = JavaVersion.toVersion(targetJavaVersion)
            if (JavaVersion.current() < javaVersion) {
                toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
            }
            withSourcesJar()
        }

        tasks.withType(JavaCompile).configureEach {
            it.options.encoding = 'UTF-8'
            it.options.compilerArgs.addAll(['-Xmaxerrs', '1000'])
            if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
                it.options.release.set(targetJavaVersion)
            }
        }

        tasks.withType(Jar).configureEach {
            from(rootProject.file('LICENSE')) {
                rename { "${it}_${rootProject.archives_base_name}" }
            }
        }
    }
}
