# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
java_version=25
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3-snapshot-7
minecraft_version_range=>=26.3-alpha.7
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric.loom.disableObfuscation=true
# Mod Properties
mod_id=mtgcard
mod_name=MtgCard
mod_author=Spider
mod_version=1.5.1-26.3-snapshot-7
maven_group=com.spider
archives_base_name=MtgCard
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.157.0+26.3
fabric_api_version_range=>=0.157.0+26.3
jei_minecraft_version=26.2
jei_version=30.19.0.148
# NeoForge Properties
neoforge_moddev_version=2.0.141
neoforge_version=26.2.0.59
neoforge_minecraft_version_range=>=26.2
neoforge_mod_version=1.5.0-26.2
neoforge_loader_version_range=[4,)
