# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
minecraft_version_range=>=26.0.0
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric.loom.disableObfuscation=true
# Mod Properties
mod_version=1.3.0-26.1.2
maven_group=com.spider
archives_base_name=MtgCard
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.146.1+26.1.2
fabric_api_version_range=>=0.144.0+26.1
jei_version=29.5.0.26
