# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
java_version=25
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
minecraft_version_range=>=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric.loom.disableObfuscation=true
# Mod Properties
mod_id=mtgcard
mod_name=MtgCard
mod_author=Spider
mod_version=1.4.1-26.2
maven_group=com.spider
archives_base_name=MtgCard
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.152.1+26.2
fabric_api_version_range=>=0.152.1+26.2
jei_minecraft_version=26.2
jei_version=30.2.0.15
# NeoForge Properties
neoforge_moddev_version=2.0.141
neoforge_version=26.2.0.8-beta
neoforge_loader_version_range=[4,)
